menu:
    Home: /
    Archives: /archives/
    Sitemap: /sitemap.xml
    # 生活: /categories/live/
    # 摄影: /categories/film/
    # 关于: /about/

widgets:
- category
- tag
- tagcloud
- archive

# count
show_count: true
favicon: /images/favicon.ico
logo: /images/logo.png

# Comment
# changyan: bubuzou
leancloud:
   appid: aD8jJBpu4oew3ovNY73z6Rdq-gzGzoHsz # 填写您的appid
   appkey: FdzS5SOPHdhYQoEUngQ8K2QW # 填写您的appkey
   comment: false # 是否开启评论系统
   timer: false # 是否开启文章统计


# Analytics
# google-analytics:
ga: UA-65933410-1

# Verification
# Baidu
baidu_verify: 1EB8XoOl0C
# Google 
google_verify: 



# Copyright Infomation
startyear: 2016

